### ISSUE TITLE
Suggestion: Add defaultTreatment to SplitView

### ISSUE THREAD

**Issue by nthorn552** [splitio/javascript-commons#225]
We have a developer tool that helps us view and override Split in our product, both for testing and for internal use and demo purposes.  I noticed `defaultTreatment` is something that is sent down to the javascript-client, but it not exposed anywhere externally.  It would be helpful if we could show this `defaultTreatment` value, so that Split is the one "source of truth" and we do not need to do something such as create our own default values in our devtool.

I have a fork of this where I tested it out and would be happy to open a PR, but I also wanted to open a thread in case the fact that I would find this property helpful is indicative of us using this tool or understanding this property's purpose incorrectly.

Proposed changes:
- Add `defaultTreatment` to the `SplitView` type
- Update `sdkManager/index.ts`'s internal `objectToView()` to include returning `defaultTreatment` property

**Comment by EmilianoSanchez** [comment]
Hi @nthorn552 , 

As you can see, the team has decided to include your suggestion about adding the `defaultTreatment` property in the SplitView object.

It will be shipped with the next release of our JS SDKs, but there is no ETA yet.

Thank you for your contribution.
